### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by karai17** [airstruck/knife#2]
Basically, your jack knife logo is meh and should be replaced with the following (or something similar):

![](https://camo.githubusercontent.com/9d4ff217e118d9fd9b2a054c9b369aecdf42bfc5/687474703a2f2f692e696d6775722e636f6d2f317a35687557652e6a7067)

**Comment by shakesoda** [comment]
I feel like the knife with scope is better for this purpose

**Comment by karai17** [comment]
True...

**Comment by airstruck** [comment]
duplicates #1 ?

**Comment by karai17** [comment]
Different issue, same pictures.


---
Landon Manning
lmanning17@gmail.com
