### ISSUE TITLE
[knife.system] create value base components

### ISSUE THREAD

**Issue by maluramichael** [airstruck/knife#3]
Is it possible to use value base components like this:

local entity = {
 position = { x = 0, y = 0},
 health = 100
}

it is possible to create and read them in a system but i cannot change the value of them. Health always stays 100.

**Comment by airstruck** [comment]
Lua has no pass-by-reference for primitives, so primitive components are generally treated as immutable in knife.system. To work around it you can use the "_entity" pseudo-component and change the value of `_entity.health`, or you can promote health to a table (maybe you want to store a max health or a "pain delta" along with the current health)?

**Comment by airstruck** [comment]
I think knife.system is due for an overhaul. I might take the entity management stuff out and let adding, removing and iterating entities all move to user code. Then we can use return values to mutate primitive components like above.

**Comment by maluramichael** [comment]
I like the way this system works and how you handle iterating. I will use a table as primitive.

**Comment by airstruck** [comment]
Too late! This might be a good time to fork it ;)

I think this is good in the long run, module code becomes much simpler and more flexible, and user code only needs one extra for-loop. This also means you'll generally only make one pass over the entities, applying all systems to each entity before processing the next, instead of making one pass for each system. This won't affect update systems much, but will make it possible to do some things in drawing systems that weren't possible before.

So you'd write:

```lua
function love.update (dt)
    for i = 1, #entities do
        updateFoo(entities[i], dt)
        updateBar(entities[i], dt)
        updateBaz(entities[i], dt)
        updateQux(entities[i], dt)
    end
end
```
Instead of:

```lua
function love.update (dt)
    updateFoo(entities, dt)
    updateBar(entities, dt)
    updateBaz(entities, dt)
    updateQux(entities, dt)
end
```

That's not so bad, right?

Here's a preview of the upcoming knife.system, will push this as soon as documentation is ready. 

```lua
local loadstring = _G.loadstring or _G.load
local tconcat = table.concat
local type = type

local function hasSigil (sigil, value)
    return type(value) == 'string' and sigil:byte() == value:byte()
end

return function (aspects, process)
    local args = {}
    local cond = {}
    local results = {}
    local localIndex = 0
    local choicePattern = '([^|]+)'

    local function suppress (aspect, condition)
        cond[#cond + 1] = 'if nil'
        for option in aspect:gmatch(choicePattern) do
            cond[#cond + 1] = condition:format(option)
        end
        cond[#cond + 1] = 'then return end'
    end

    local function supply (aspect, isOptional, isReturned)
        localIndex = localIndex + 1
        cond[#cond + 1] = ('local l%d = nil'):format(localIndex)
        for option in aspect:gmatch(choicePattern) do
            cond[#cond + 1] = ('or _entity[%q]'):format(option)
        end
        if not isOptional then
            cond[#cond + 1] = ('if not l%d then return end'):format(localIndex)
        end
        if isReturned then
            results[#results + 1] = ('_entity[%q]'):format(aspect)
        end
        args[#args + 1] = ('l%d'):format(localIndex)
    end

    for index = 1, #aspects do
        local aspect = aspects[index]
        if hasSigil('_', aspect) then
            args[#args + 1] = aspect
        elseif hasSigil('!', aspect) or hasSigil('~', aspect) then
            suppress(aspect:sub(2), 'or _entity[%q]')
        elseif hasSigil('-', aspect) then
            suppress(aspect:sub(2), 'or not _entity[%q]')
        elseif hasSigil('?', aspect) then
            supply(aspect:sub(2), true)
        elseif hasSigil('=', aspect) then
            supply(aspect:sub(2), false, true)
        else
            supply(aspect, false)
        end
    end

    local source = ([[
local _aspects, _process = ...
return function (_entity, ...) 
    %s
    %s _process(%s ...)
    return true
end]]):format(
        tconcat(cond, ' '),
        results[1] and (tconcat(results, ',') .. ' = ') or '',
        args[1] and (tconcat(args, ', ') .. ', ') or '')
        
    return loadstring(source)(aspects, process)
end
```
