### ISSUE TITLE
Could you please write micro-modules call spawn to use with chain

### ISSUE THREAD

**Issue by takaaptech** [airstruck/knife#5]
Hi,
Your chain module is awesome! I use it for chain many animation actions together. But i also want to using spawn actions with chain too. For example:
I want to move and scale object play in same time and then chain with other move?
(Actually, i want using chain and spawn like this: http://www.cocos2d-x.org/wiki/Actions)
Thank so much!

**Comment by airstruck** [comment]
Hi, glad you're enjoying Chain!

You want to be able to do something like this, is that right?

```lua
Chain(
    function (go)
        asyncFunc(go)
        otherAsyncFunc(go)
    end,
    function (go)
        print 'this happens after both async functions finish'
    end
)()
```

What about something like this?

```lua
local function spawn (n, go)
    return function (...)
        n = n - 1
        if n == 0 then go(...) end
    end
end
```

You could use it like this:

```lua
Chain(
    function (go)
        go = spawn(2, go)
        asyncFunc(go)
        otherAsyncFunc(go)
    end,
    function (go)
        print 'this happens after both async functions finish'
    end
)()
```

I haven't tested it but it looks like it should work. Let me know what you think, I think it's too small to add a module for, but maybe it can be a note in the docs?

What about callbacks that pass arguments to `go`, though? Arguments to `go` are passed through to the next "link" in the chain, how should this be handled in this case?

**Comment by takaaptech** [comment]
Incredible that it is works! i feel like we are playing with lego pieces 👯 
I just tested and it works! Thank so much for quickly answer!
`local function move(go)
	-- body
	print("move ")
	print("and then.. after some wait")
	go()
end

local function scale(go)
	-- body
	print("scale ")
	print("and then .. after some wait")
	go()
end


local function spawn (n, go)
    return function (...)
        n = n - 1
        if n == 0 then go(...) end
    end
end

local function MoveAndScale(go)
    go = spawn(2, go)
    move(go)
    scale(go)
end


local function callback(go)
	-- body
	print("Yes, it is just works!")
end

local action = Chain(MoveAndScale,callback)

action()`
The only think i am concerned is how to write code more naturally like this:

`local spawn_action = Spawn(move,scale)
local action = Chain(spawn_action,callback)
action()
`

I still thinking about how to use your lego pieces to make Spawn function like that ...

**Comment by airstruck** [comment]
Hmm, what about this?

```lua
local function Spawn (...)
    local t = { ... }
    return function (go, ...)
        local n = #t
        local function cb (...)
            n = n - 1
            if n == 0 then go(...) end
        end
        for _, func in ipairs(t) do
            func(cb, ...)
        end
    end
end
```

Again untested, but something like this might work.

**Comment by takaaptech** [comment]
Excellent! It is power of Chain, thank you so much!
